### ISSUE TITLE
NavBar not working for mobile displays

### ISSUE THREAD

**Issue by adityarai0705** [sanskaromar/renaissance-2k23#25]
**Nav bar does not work in small displays**
The moment, the burger icon is clicked, the whole screen becomes white with several error logs from the navbar component

https://user-images.githubusercontent.com/44937487/218709556-b1330b2
<img width="805" alt="Screenshot 2023-02-14 at 3 54 22 PM" src="https://user-images.githubusercontent.com/44937487/218709660-86c26613-5c65-4ab3-a9b3-1293699cd30d.png">
7-7056-4f24-bf14-4038f3f3efa0.mov

**Comment by samjain233** [comment]
I have resolved this issue
