### ISSUE TITLE
Events page is not responsive

### ISSUE THREAD

**Issue by adityarai0705** [sanskaromar/renaissance-2k23#26]
**Events page is not responsive**

<img width="771" alt="Screenshot 2023-02-14 at 3 51 29 PM" src="https://user-images.githubusercontent.com/44937487/218710670-cd57b89c-d5ab-4302-99d5-5035a05857d2.png">

**Comment by adityarai0705** [comment]
<img width="576" alt="Screenshot 2023-02-14 at 4 10 09 PM" src="https://user-images.githubusercontent.com/44937487/218712007-ec8c052f-23df-4916-ae1f-430bc919bd14.png">

**Comment by Cyber-Infernox** [comment]
Can I please solve this issue?

**Comment by sanskaromar** [comment]
Resolved by #51
