### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by adityarai0705** [sanskaromar/renaissance-2k23#27]
**Event's background colour and Footer's icon's margins**

The Event's background colour was supposed to be #2F3E46 according to the design but #345F52 was used instead.

The social icons in Footer lack margins on display with a width greater than 1023px.

<img width="272" alt="Screenshot 2023-02-14 at 3 50 05 PM" src="https://user-images.githubusercontent.com/44937487/218713504-8701e465-f346-46ad-9ef9-de75c29483e4.png">

**Comment by Sambhav-Sam** [comment]
I want to work on this.
