### ISSUE TITLE
hover animations in buttons 

### ISSUE THREAD

**Issue by samjain233** [sanskaromar/renaissance-2k23#28]
I think we should add nice looking hover animation effect in buttons , this would better User experience 

![image](https://user-images.githubusercontent.com/94921996/218757789-2d90f85c-560f-4026-a09c-a6c496ea7477.png)
![image](https://user-images.githubusercontent.com/94921996/218757944-22c2acbb-1463-47ea-b28d-c7b83799ac3b.png)
![image](https://user-images.githubusercontent.com/94921996/218757969-96244012-67c5-4d40-a12a-069100fef0b6.png)

I has tried to give animation effect effect in above two buttons and it is looking like this :- 
https://user-images.githubusercontent.com/94921996/218759381-a52981d6-0d8d-4007-9b85-4c3dc16b04a2.mp4

**Comment by PANDEYS432** [comment]
![Screenshot (536)](https://user-images.githubusercontent.com/98703881/218772771-b38df35b-760e-4650-b509-7e5a25ff4dde.png)
also in read more hover effect missing
