### ISSUE TITLE
padding-y in footer component in large viewport is missing and copywrite content missing at bottom

### ISSUE THREAD

**Issue by PANDEYS432** [sanskaromar/renaissance-2k23#31]
![Screenshot (537)](https://user-images.githubusercontent.com/98703881/218769729-f9ddea24-9ab9-4772-a327-88500cbdbb77.png)

copywrite content is missing 
py is missing in large view port or laptop view
also bit of margin should be reduced between texts

**Comment by PANDEYS432** [comment]
![Uploading Screenshot (537).png…]()

**Comment by Tushar00002** [comment]
made a pr regarding this issue
