### ISSUE TITLE
Auth component is getting blank for small viewport and mobile view

### ISSUE THREAD

**Issue by PANDEYS432** [sanskaromar/renaissance-2k23#33]
![Screenshot (540)](https://user-images.githubusercontent.com/98703881/218769484-f3167e5b-33be-4006-a832-f80bef3c91cf.png)
on clicking whole page gets blank for mobile view or below 640px

**Comment by samjain233** [comment]
I had resolved this . Assign it to me

**Comment by Ashish-Verma-MNNIT** [comment]
Closing this issue as it is a duplicate of issue #25
