### ISSUE TITLE
splitting of text in two parts in mobile view

### ISSUE THREAD

**Issue by samjain233** [sanskaromar/renaissance-2k23#46]
![image](https://user-images.githubusercontent.com/94921996/219038417-03f765b4-3711-43ac-b88d-1f9c073ec16b.png)

**Comment by Tushar00002** [comment]
Fixed this issue
![Screenshot (422)](https://user-images.githubusercontent.com/102597162/219050614-72926f14-bd9f-44a3-9025-1df4cb68c902.png)
